import { Item } from '../typescript/Interface';

export const ICONS_ITEM: Item[] = [
	{
		name: 'Boxicons',
		tag: ['Icons'],
		description:
			'Simple open source icons carefully crafted for designers & developers.',
		img: '/imgs/content/Boxicons.webp',
		alt: 'Boxicons. Simple open source icons carefully crafted for designers & developers.',
		link: 'https://boxicons.com/',
	},
	{
		name: 'CanInclude',
		tag: ['Tools'],
		description:
			'Check if you can include one library in another library or framework.',
		img: '/imgs/content/Caninclude.webp',
		alt: 'CanInclude. Check if you can include one library in another library or framework.',
		link: 'https://www.caninclude.glitch.me/',
	},
	{
		name: 'Crypto Logos',
		tag: ['Icons'],
		description: 'High quality cryptocurrency logos.',
		img: '/imgs/content/CryptoLogos.webp',
		alt: 'Crypto Logos. High quality cryptocurrency logos.',
		link: 'https://cryptologos.cc/',
	},
	{
		name: 'Css Gradient',
		tag: ['Tools'],
		description: 'A simple tool to generate CSS gradients.',
		img: '/imgs/content/Cssgradient.webp',
		alt: 'Css Gradient. A simple tool to generate CSS gradients.',
		link: 'https://cssgradient.io/',
	},
	{
		name: 'Css Icons',
		tag: ['Icons'],
		description: 'Open-source CSS, SVG and Figma UI icons.',
		img: '/imgs/content/CssIcons.webp',
		alt: 'Css Icons. Open-source CSS, SVG and Figma UI icons.',
		link: 'https://css.gg/',
	},
	{
		name: 'Css loaders',
		tag: ['Tools'],
		description: 'A collection of loading spinners animated with CSS.',
		img: '/imgs/content/Cssloaders.webp',
		alt: 'Css loaders. A collection of loading spinners animated with CSS.',
		link: 'https://css-loaders.com/',
	},
	{
		name: 'Flaticon',
		tag: ['Icons'],
		description: 'Access 16.2M+ vector icons & stickers.',
		img: '/imgs/content/Flaticon.webp',
		alt: 'FlatIcon. Access 16.2M+ vector icons & stickers.',
		link: 'https://www.flaticon.com/',
	},
	{
		name: 'Heroicons',
		tag: ['Icons'],
		description:
			'Beautiful hand-crafted SVG icons, by the makers of Tailwind CSS.',
		img: '/imgs/content/heroicons.webp',
		alt: 'Heroicons. Beautiful hand-crafted SVG icons, by the makers of Tailwind CSS.',
		link: 'https://heroicons.com/',
	},
	{
		name: 'Html reference',
		tag: ['Tools'],
		description:
			'A free guide to HTML. It features all elements and attributes.',
		img: '/imgs/content/Htmlreference.webp',
		alt: 'Html reference. A free guide to HTML. It features all elements and attributes.',
		link: 'https://htmlreference.io/',
	},
	// {
	// 	name: 'Icon Maker',
	// 	tag: ['Icons'],
	// 	description: 'Create your own icons from scratch.',
	// 	img: '/imgs/content/IconMaker.png',
	// 	link: 'https://iconmaker.io/',
	// },
	{
		name: 'Iconoir',
		tag: ['Icons'],
		description: 'A high-quality selection of free icons.',
		img: '/imgs/content/Iconoir.webp',
		alt: 'Iconoir. A high-quality selection of free icons.',
		link: 'https://iconoir.com/',
	},
	{
		name: 'iloveIMG',
		tag: ['Tools'],
		description: 'Every tool you could want to edit images in bulk.',
		img: '/imgs/content/iloveimg.webp',
		alt: 'iloveIMG. Every tool you could want to edit images in bulk.',
		link: 'https://www.iloveimg.com/',
	},
	{
		name: 'Lucide',
		tag: ['Icons'],
		description: 'Beautiful & consistent icons.',
		img: '/imgs/content/Lucide.webp',
		alt: 'Lucide. Beautiful & consistent icons.',
		link: 'https://lucide.dev/',
	},
	{
		name: 'Material UI',
		tag: ['Libraries'],
		description:
			'MUI provides a simple, customizable, and accessible library of React components.',
		img: '/imgs/content/Mui.webp',
		alt: 'Material UI. MUI provides a simple, customizable, and accessible library of React components.',
		link: 'https://mui.com/',
	},
	{
		name: 'NextUI',
		tag: ['Libraries'],
		description: 'Beautiful, fast and modern React UI library.',
		img: '/imgs/content/NextUI.webp',
		alt: 'NextUI. Beautiful, fast and modern React UI library.',
		link: 'https://nextui.org/',
	},
	{
		name: 'Shadcn',
		tag: ['Components'],
		description:
			'Beautifully designed components that you can copy and paste into your apps.',
		img: '/imgs/content/Shadcn.webp',
		alt: 'Shadcn. Beautifully designed components that you can copy and paste into your apps.',
		link: 'https://ui.shadcn.com/',
	},
	{
		name: 'Squoosh',
		tag: ['Tools'],
		description:
			'The ultimate image optimizer that allows you to compress and compare images with different codecs in your browser.',
		img: '/imgs/content/Squoosh.webp',
		alt: 'Squoosh. The ultimate image optimizer that allows you to compress and compare images with different codecs in your browser.',
		link: 'https://squoosh.app/',
	},
	{
		name: 'Svg Repo',
		tag: ['Icons'],
		description:
			'Search, explore and edit the best-fitting free icons or vectors for your projects.',
		img: '/imgs/content/SvgRepo.webp',
		alt: 'Svg Repo. Search, explore and edit the best-fitting free icons or vectors for your projects.',
		link: 'https://www.svgrepo.com/',
	},
	{
		name: 'Tailwind components',
		tag: ['Tailwind'],
		description:
			'A free repository for community components using Tailwind CSS.',
		img: '/imgs/content/Tailwindcomponents.webp',
		alt: 'Tailwind components. A free repository for community components using Tailwind CSS.',
		link: 'https://tailwindcomponents.com/',
	},
	{
		name: 'Tinypng',
		tag: ['Tools'],
		description: 'Smart WebP, PNG and JPEG compression for faster websites.',
		img: '/imgs/content/Tinypng.webp',
		alt: 'Tinypng. Smart WebP, PNG and JPEG compression for faster websites.',
		link: 'https://tinypng.com/',
	},
	{
		name: 'Yesicon',
		tag: ['Icons'],
		description: 'High-Quality Vector Icons from Top Design Teams.',
		img: '/imgs/content/Yesicon.webp',
		alt: 'Yesicon. High-Quality Vector Icons from Top Design Teams.',
		link: 'https://www.yesicon.app/',
	},
];
